selftests/hacks: get everything cross building
Signed-off-by: Tyler Baker <tyler.baker@linaro.org>

diff --git a/tools/testing/selftests/mqueue/Makefile b/tools/testing/selftests/mqueue/Makefile
--- a/tools/testing/selftests/mqueue/Makefile
+++ b/tools/testing/selftests/mqueue/Makefile
@@ -1,8 +1,11 @@
-CFLAGS = -O2
+CFLAGS += -O2
+CFLAGS += -I../../../../usr/include/
+LDLIBS += -L../../../../usr/include/
+LDLIBS += -lrt -lpthread -lpopt
 
 all:
-	$(CC) $(CFLAGS) mq_open_tests.c -o mq_open_tests -lrt
-	$(CC) $(CFLAGS) -o mq_perf_tests mq_perf_tests.c -lrt -lpthread -lpopt
+	$(CC) $(CFLAGS) mq_open_tests.c -o mq_open_tests $(LDLIBS)
+	$(CC) $(CFLAGS) -o mq_perf_tests mq_perf_tests.c $(LDLIBS)
 
 include ../lib.mk
 
@@ -14,8 +17,8 @@ endef
 TEST_PROGS := mq_open_tests mq_perf_tests
 
 override define EMIT_TESTS
-	echo "./mq_open_tests /test1 || echo \"selftests: mq_open_tests [FAIL]\""
-	echo "./mq_perf_tests || echo \"selftests: mq_perf_tests [FAIL]\""
+	echo "(./mq_open_tests /test1  && echo \"selftests: mq_open_tests [PASS]\") || echo \"selftests: mq_open_tests [FAIL]\""
+	echo "(./mq_perf_tests  && echo \"selftests: mq_perf_tests [PASS]\") || echo \"selftests: mq_perf_tests [FAIL]\""
 endef
 
 clean:
